version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "job-portal-profile-refresh"
s3_prefix = "job-portal-profile-refresh"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SecretName=\"job-portal-credentials\" LogLevel=\"info\""
image_repositories = []

[default.build]
[default.build.parameters]
cached = true
parallel = true
